
name: Hello World Workflow


on:
  pull_request: 
    branches: [main]
    types: [closed]
  push:
    branches: [main]
    types: [closed]

jobs:
  simple_hello_world:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "JESUS CHRIST IS LORD!"
